ignore_actions:
  - name: dw-zenid/tfaction/setup
  - name: dw-zenid/tfaction/test-module
  - name: dw-zenid/tfaction/plan
  - name: dw-zenid/tfaction/apply
  - name: dw-zenid/tfaction/list-targets
  - name: dw-zenid/tfaction/export-secrets
  - name: dw-zenid/tfaction/get-target-config
  - name: dw-zenid/tfaction/test
  - name: dw-zenid/tfaction/set-drift-env
  - name: dw-zenid/tfaction/scaffold-working-dir
  - name: dw-zenid/tfaction/update-drift-issue
  - name: dw-zenid/tfaction/create-follow-up-pr
  - name: dw-zenid/tfaction/release-module
  - name: dw-zenid/tfaction/scaffold-module
  - name: dw-zenid/tfaction/create-scaffold-module-pr
  - name: dw-zenid/tfaction/create-scaffold-pr
  - name: dw-zenid/tfaction/scaffold-tfmigrate
  - name: dw-zenid/tfaction/terraform-plan
  - name: dw-zenid/tfaction/sync-drift-issue-description
  - name: dw-zenid/tfaction/terraform-apply
  - name: dw-zenid/tfaction/tfmigrate-apply
  - name: dw-zenid/tfaction/get-global-config
  - name: dw-zenid/tfaction/list-working-dirs
  - name: dw-zenid/tfaction/list-targets-with-changed-files
  - name: dw-zenid/tfaction/list-changed-modules
  - name: dw-zenid/tfaction/tfmigrate-plan
  - name: dw-zenid/tfaction/export-aws-secrets-manager
  - name: dw-zenid/tfaction/deploy-ssh-key
  - name: dw-zenid/tfaction/check-terraform-skip
