---
name: Prettier
on: workflow_call

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm i
      - run: npm t
