---
name: Prettier
on: workflow_call

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm i
      - run: npm t
