---
name: test-list-working-dirs
on: workflow_call

jobs:
  test-list-working-dirs:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.27.1
      - uses: ./list-working-dirs
        id: working_dirs
        env:
          TFACTION_CONFIG: list-working-dirs/tests/tfaction-root.yaml
      - run: cat "${{ steps.working_dirs.outputs.file }}"
