---
name: test-list-working-dirs
on: workflow_call

jobs:
  test-list-working-dirs:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.27.1
      - uses: ./list-working-dirs
        id: working_dirs
        env:
          TFACTION_CONFIG: list-working-dirs/tests/tfaction-root.yaml
      - run: cat "${{ steps.working_dirs.outputs.file }}"
